name: Auto Daily Commits

on:
  schedule:
    - cron: "0 7 * * *"   # 7 AM UTC (adjust if needed)
    - cron: "0 14 * * *"  # 2 PM UTC
    - cron: "0 21 * * *"  # 9 PM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # So we can push later

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run auto commit script
        run: node index.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🤖 Auto commit from GitHub Actions" || echo "No changes to commit"
          git push origin HEAD:main
